version: '3.1'
services:
  threatdragon:
    hostname: threatdragon
    container_name: threatdragon
    image: owasp/threat-dragon:v2.0.8
    ports:
      - "8080:8080"
    volumes:
      - "./config.env:/app/.env"
