name: Docker Image CI

on: [push, pull_request, workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: prepare Test
      run: chmod +x test/validateDockerComposeSetUp.sh
    
    - name: execute Test
      run: test/validateDockerComposeSetUp.sh
